#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    #alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Put your fun stuff here
export LD_LIBRARY_PATH=/usr/local/lib

# 42 Madrid Stuff

alias old_norminette="~/.norminette/norminette.rb"
CFLAGS="-Wall -Wextra -Werror"
#USER="aperez-b"
MAIL="marvin@42.fr"
alias libft_test="bash ~/Libftest/grademe.sh"
alias libft_test2="builtin cd ~/42Madrid/GitHub/42-Madrid-Cursus/libft-unit-test/ && make f && builtin cd"
alias libft_test3="bash ~/libft-war-machine/grademe.sh"
alias libft_test4="builtin cd ~/42Madrid/GitHub/42-Madrid-Cursus/libft/libftTester && make a && builtin cd"

# Custom Google greeting
# bash ~/.mygreeting

# Custom 42 greeting
bash ~/.mygreeting42

# Aliases (custom)
alias downs="cd ~/Downloads"
alias docs="cd ~/Documents"
alias music="cd ~/Music"
alias x="clear && ls -a"
alias scc="yay -Scc"
alias gdrive="cd ~/Google\ Drive"
alias desktop="cd ~/Desktop"
alias r="clear && source ~/.bashrc && builtin cd"
alias q="exit"
alias u="yay -Syu --noconfirm"
alias tether="gnirehtet run"
alias unwine="wine uninstaller"
alias apps="builtin cd /usr/share/applications && ls /usr/share/applications"
alias appicons="builtin cd /usr/share/icons && ls /usr/share/icons"
alias localapps="builtin cd ~/.local/share/applications && ls ~/.local/share/applications"
alias h="cd ~/ && l -a -L 1"
alias bashrc="nano ~/.bashrc"
alias bashrc_update="cp ~/.bashrc ~/Google\ Drive/Chrome\ OS/Crostini/Bashrc/.bashrc"
alias removable="cd ~/Removable\ Devices"
alias ext="cd ~/Removable\ Devices"
alias v="neofetch | lolcat"
alias l="echo -e '\n\e[1;33mThis directory has the following:\e[0m' && tree -L 2 -C --filelimit 100"
alias sp="spotdl"
alias yoump3="youtube-dl -x --audio-format mp3"
alias pipupdate="sudo pip install -U"
alias pamac-fix="zcat /usr/share/app-info/xmls/community.xml.gz | sed 's|<em>||g;s|<\/em>||g;' | gzip > 'new.xml.gz' && sudo cp new.xml.gz /usr/share/app-info/xmls/community.xml.gz && sudo appstreamcli refresh-cache --force"
alias yan="yay --noconfirm --needed"
alias checktheme-now="python -u '/home/chronos/.autotheme/timecheck-now.py'"
alias checktheme="systemctl --user status auto-theme"
alias checktheme-timer="systemctl --user status auto-theme.timer"
alias donkeykong="python -u '/home/chronos/Google Drive/Uc3m/Data Science & Engineering/Year 1/1st Term/Programming 1/Donkey Kong/mario_barrel.py'"
alias vbmeta="fastboot --disable-verity --disable-verification flash vbmeta /home/chronos/.vbmeta/vbmeta.img && fastboot reboot"
alias timeconvert="python -u /home/chronos/Removable\ Devices/Pixel\ SD/Fun\ Python\ Scripts/Timeconverter/timeconverter.py"
alias sp_update="sudo pip install https://codeload.github.com/spotDL/spotify-downloader/zip/master"

# Functions (custom)
function b() {
  if [ $# -eq 0 ]; then
    count=1
  else
    count="$1"
  fi

  i=0
  while [ $i -lt $count ]; do
    builtin cd '..'
    i=$((i+1))
  done
  l
}

function up() {
  if [ $# -eq 0 ]; then
    count=1
  else
    count="$1"
  fi

  i=0
  while [ $i -lt $count ]; do
    builtin cd '..'
    i=$((i+1))
  done
  l
}

function cd() {
    new_directory="$*";
    if [ $# -eq 0 ]; then
        new_directory=${HOME};
    fi;
    l "${new_directory}" && builtin cd "${new_directory}"
}

function mkcdir() {
    mkdir -p -- "$1" &&
    cd "$1"
}

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
